baseURL = "https://jav-car-1971.github.io/"
languageCode = "es"
title = "Mi Nuevo Sitio"
theme = "coder"
contentDir = "content/es"
enableRobotsTXT = true
paginate = 5 # He añadido esto para que la lista de posts se pagine si tienes muchos

[params]
    author = "Javier Caram"
    info = "Desarrollador y Creador"
    description = "El sitio de Javier Caram."
    colorscheme = "auto"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Sobre mí"
    url = "/about/"
    weight = 2
