baseURL = "https://jav-car-1971.github.io/english"
languageCode = "en"
title = "Mi Nuevo Sitio"
theme = "coder"
contentDir = "content/en"
enableRobotsTXT = true
paginate = 5 # He añadido esto para que la lista de posts se pagine si tienes muchos

[params]
    author = "Javier Caram"
    info = "dev"
    description = "JavCar1971"
    colorscheme = "auto"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Sobre mí"
    url = "/about/"
    weight = 2
