baseURL = "https://coperniciodev.github.io/english/"
languageCode = "en"
title = "New Site"
theme = "coder"
contentDir = "content/en"
enableRobotsTXT = true
paginate = 5 # He añadido esto para que la lista de posts se pagine si tienes muchos

[params]
    author = "copernicio.dev"
    info = "dev"
    description = "copernicio.dev"
    colorscheme = "auto"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
